# Generated by Django 4.2.25 on 2025-10-20 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ism-sharif')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject', models.CharField(max_length=150, verbose_name='Mavzu')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Aloqa xabari',
                'verbose_name_plural': 'Aloqa xabarlari',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_code', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Kuzatuv kodi')),
                ('appeal_type', models.CharField(choices=[('Pora', "To'g'ridan-to'g'ri Pora talabi"), ('Homiylik', 'Noqonuniy Homiylik/Grant'), ('Ishga joylashish', 'Ishga joylashishdagi Korrupsiya'), ('Davlat xaridi', "Davlat xaridlarida suiiste'mol"), ('Boshqa', 'Boshqa turdagi holat')], max_length=100, verbose_name='Murojaat turi')),
                ('full_name', models.CharField(blank=True, max_length=150, verbose_name='F.I.Sh')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Telefon')),
                ('message', models.TextField(verbose_name='Xabar matni')),
                ('file', models.FileField(blank=True, null=True, upload_to='uploads/', verbose_name='Biriktirilgan fayl')),
                ('status', models.CharField(choices=[('pending', 'Ko‘rib chiqilmoqda'), ('resolved', 'Hal qilingan')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
            ],
            options={
                'verbose_name': 'Murojaat (Report)',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
