# Generated by Django 4.2.25 on 2025-10-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Ko‘rib chiqilmoqda'), ('resolved', 'Hal qilingan'), ('rejected', 'Rad etilgan')], default='pending', max_length=20),
        ),
    ]
